### ISSUE TITLE
Can't composer update

### ISSUE THREAD

**Issue by monsterdream** [kawankoding/laravel-fcm#1]
First issue :)
Basically it's working nice, it's installing, after adding it to ServiceProviders it's also working nice but then I'm blocked because command composer update is throwing an error:
```
> php artisan clear-compiled

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Class 'Kawankoding\Fcm\Providers\FcmServiceProvider' not found

Script php artisan clear-compiled handling the post-update-cmd event returned with error code 1
```

**Comment by mai92** [comment]
I've update the directory structure and readme , and check it working now :) , try to `composer remove kawankoding/laravel-fcm` then install it again by `composer require kawankoding/laravel-fcm` , also register the service provider like the updated readme

**Comment by monsterdream** [comment]
Thanks man! Awesome work!

**Comment by mai92** [comment]
You're welcome, thanks for open an issue also..
