### ISSUE TITLE
No support for laravel 4.2?

### ISSUE THREAD

**Issue by aroramohit** [kawankoding/laravel-fcm#11]
I tried to install the library in the laravel 4.2 project and it showed me error while i tried this command

$ composer require kawankoding/laravel-fcm

Is your library compatible with laravel 4.2 and php 5.6?

**Comment by aroramohit** [comment]
- kawankoding/laravel-fcm 0.1.1 requires illuminate/support ~5.1.0|~5.2.0|~5.3.0|~5.4.0|~5.5.0|~5.6.0 -> satisfiable by illuminate/support[v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.1
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.13
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.16
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.2
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.20
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.22
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.25
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.28
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.30
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.31
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.41
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.6
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.1.8
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.0
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.19
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.21
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.24
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.25
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.26
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.27
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.28
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.31
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.32
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.37
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.43
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.45
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.6
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.2.7
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.3.0
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.3.16
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.3.23
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.3.4
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.4.0
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.4.13
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.4.17
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.4.19
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.4.27
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.4.36
    - don't install laravel/framework v4.2.0|don't install illuminate/support v5.4.9
    - Installation request for laravel/framework 4.2.* -> satisfiable by laravel/framework[v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.13, v4.2.14, v4.2.15, v4.2.16, v4.2.17, v4.2.18, v4.2.19, v4.2.2, v4.2.20, v4.2.21, v4.2.22, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, 4.2.x-dev].

**Comment by mai92** [comment]
@aroramohit sorry, this package is build for laravel 5 above

**Comment by aroramohit** [comment]
Okay. 
Any suggestions for laravel 4.2 for FCM notifications?

**Comment by SamerDiab** [comment]
@aroramohit  Yes, upgrade your laravel to 5.7 :D
