### ISSUE TITLE
i need example for sending from controller

### ISSUE THREAD

**Issue by alimuhnad** [kawankoding/laravel-fcm#14]
i need to send notfy by using controller plz help?

**Comment by mai92** [comment]
you can use this code direct on your controller `fcm()
    ->toTopic($topic) // $topic must an string (topic name)
    ->notification([
        'title' => 'Test FCM',
        'body' => 'This is a test of FCM',
    ])
    ->send();`

**Comment by mai92** [comment]
`fcm()
    ->toTopic($topic) // $topic must an string (topic name)
    ->notification([
        'title' => 'Test FCM',
        'body' => 'This is a test of FCM',
    ])
    ->send();`

**Comment by mai92** [comment]
please check the documentation once more

**Comment by alimuhnad** [comment]
thank you for replay ...... how can i use it directly without call it from the model ??? i trying to use it on ionic 3 
i have one more Q. 
if i want to send notfcation for one user 
its need token how can i get it ?

**Comment by JoseGeorges8** [comment]
@alimuhnad you get the token from your frontend device. With ionic you could use the firebase plugin [here](https://ionicframework.com/docs/native/firebase)
