### ISSUE TITLE
polish chars problem

### ISSUE THREAD

**Issue by binar123** [kawankoding/laravel-fcm#15]
hi
everything works fin but when im sending text with polish characters message is not sending 
is it possible to make some kind of debug on this fascade ?
send function 
```
 FcmFacade::toTopic(env('FCM_TOPIC'))
        ->notification($data)
            ->send();
```

**Comment by erlangparasu** [comment]
Hi @binar123, maybe you can try to enable debug response. then check the firebase log in the `laravel.log` file.
```
fcm()
    ->to($recipients)
    // ...
    ->enableResponseLog()
    ->send();
```
