### ISSUE TITLE
Need an example 

### ISSUE THREAD

**Issue by iamkatta** [kawankoding/laravel-fcm#17]
Hello,

Could you please help us in using this package, I did not get what recipient is.

fcm()
    ->to(**$recipients**) // $recipients must an array
    ->data([
        'title' => 'Test FCM',
        'body' => 'This is a test of FCM',
    ])
    ->send();

Thanks

**Comment by mai92** [comment]
Hello @iamkatta $recipients is FCM IDs from your mobile dev get from Firebase :)

**Comment by erlangp** [comment]
https://stackoverflow.com/questions/42930394/how-to-get-registration-ids-from-firebase-fcm/42933101#42933101 :)

**Comment by iamkatta** [comment]
thanks for reply guys
