### ISSUE TITLE
Wrong payload data

### ISSUE THREAD

**Issue by bishalkc** [kawankoding/laravel-fcm#18]
Hello, 

Just an FYI the payload flag has a typo in src/Fcm.php 

`
        $fields = [
            '**content-available**' => true,
            'priority' => 'high',
            'data' => $this->data,
            'notification' => $this->notification
        ];
`
should be 
`
        $fields = [
            '**content_available**' => true,
            'priority' => 'high',
            'data' => $this->data,
            'notification' => $this->notification
        ];
`

**Comment by mai92** [comment]
Thank you for correction, i have corrected it
