### ISSUE TITLE
Data Questions

### ISSUE THREAD

**Issue by nam-co** [kawankoding/laravel-fcm#27]
Hi, thank you for the package, I was wondering if its possible to send additional data, for example buttons and actions in the push notifications, thanks for you work

**Comment by erlangp** [comment]
currently it's not possible https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidNotification
you will need to send any custom data using `->data($arr)` instead of `->notification($arr)`, than handle data and manually setup notification UI before display it to the user
