### ISSUE TITLE
Push notification not working

### ISSUE THREAD

**Issue by kossa** [kawankoding/laravel-fcm#35]
Hello,

I'm trying to use this package, it's very simple and awesome, but it does not works,

Here is the code :
![image](https://user-images.githubusercontent.com/1175584/68104816-d0bfc600-fedc-11e9-8fdd-c1716db961e7.png)

And the response in browser: 
![image](https://user-images.githubusercontent.com/1175584/68104822-d61d1080-fedc-11e9-9aa6-7d16f48d1ee9.png)

I did not receive any notification, when I try from firebase I got it :
![image](https://user-images.githubusercontent.com/1175584/68104869-019ffb00-fedd-11e9-9eb7-88fc825c0bd4.png)

**Comment by erlangp** [comment]
after priority, try add `->timeToLive(0)` sir

**Comment by erlangp** [comment]
and try using  
```
    ->notification([
        'title' => 'Test FCM',
        'body' => 'This is a test of FCM',
    ])
```

instead of `->data(`
to achieve behavior like Firebase Console sir

**Comment by kossa** [comment]
Alright, works fine, but it does not exist in the readme file

**Comment by erlangp** [comment]
by default, Firebase seever will queue your notification in 4 weeks

**Comment by kossa** [comment]
Nice to know thank you @erlangp

**Comment by ahmedkamel1192** [comment]
response return null !!! how can i get response

**Comment by erlangp** [comment]
@ahmedkamel1192 please provide your code sir :)

**Comment by erlangparasu** [comment]
Hi, @ahmedkamel1192.. maybe you can try to enable debug response. then check the firebase log in the `laravel.log` file.
```
fcm()
    ->to($recipients)
    // ...
    ->enableResponseLog()
    ->send();
```
