### ISSUE TITLE
Question: offline app

### ISSUE THREAD

**Issue by kossa** [kawankoding/laravel-fcm#37]
Hello,

What if I send a push to user that has not internet, once he connect, he'll not receive the push, how to fix that ?

Thank you

**Comment by erlangp** [comment]
hello.. need to  call and increase `->timeToLive(60 * 60 * 24)` 
message still in Firebase Server in 24hor

**Comment by kossa** [comment]
Thank you to help me again :)

Alright, you have to add this in doc

**Comment by erlangparasu** [comment]
Thanks @kossa .. i just added note about time to live configuration in readme
