### ISSUE TITLE
Lumen Throw Error

### ISSUE THREAD

**Issue by andriyandriyan** [kawankoding/laravel-fcm#43]
Hi, thank you for the package, but I get this error when implementing to Lumen 7.0
`Call to undefined function Kawankoding\\Fcm\\config_path()`

**Comment by mai92** [comment]
Hi @andriyandriyan originally this package built for Laravel & maybe you face the error because lumen not provide helper for config_path()

**Comment by andriyandriyan** [comment]
Fix with this [PR](https://github.com/kawankoding/laravel-fcm/pull/44)
