### ISSUE TITLE
get push notifications results

### ISSUE THREAD

**Issue by firmanmikhsan** [kawankoding/laravel-fcm#47]
hello, i want to know how to get notification result. i want to check if notification sent successfully or error.

sorry for bad english
Thanks in advance

**Comment by godiez** [comment]
Hi,

As you can see in the [https://github.com/kawankoding/laravel-fcm/blob/master/src/Fcm.php#L76](send()) function, returns the response as follows:

`array:5 [
  "multicast_id" => XXXXXXXXXXXXXX
  "success" => 1
  "failure" => 0
  "canonical_ids" => 0
  "results" => array:1 [
    0 => array:1 [
      "message_id" => "X:XXXXXXXXX"
    ]
  ]
]
`

"success" show if the notifications have been sent correctly.
