### ISSUE TITLE
working fine on local but not on production

### ISSUE THREAD

**Issue by preetsodha** [kawankoding/laravel-fcm#55]
laravel-FCM notification working on local but not on production. My domain is ssl enabled. is it creating issue.

i try
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

but its still not working

here is my code...

 $firebaseToken = User::where('id',$user->id)->whereNotNull('device_token')->pluck('device_token');

       $recipients =  $firebaseToken->toArray();
        fcm()
          ->to($recipients)
          ->priority('high')
          ->timeToLive(0)
          ->data([
              'title' => $title,
              'body'  => $body,
          ])
          ->send();

**Comment by erlangp** [comment]
hi, can you plase try to log the curl response (log before json_decode) using laravel logger() ? then post the result here.. thank you

**Comment by poojakbs** [comment]
i am getting this as response

"{\"multicast_id\":3417515367515540322,\"success\":0,\"failure\":1,\"canonical_ids\":0,\"results\":[{\"error\":\"NotRegistered\"}

i have notice that notification works fine from postman. but its not worked from mobile app

**Comment by poojakbs** [comment]
i tried on different devices. i got the notification on some devices. but its blank . without title and body.

**Comment by preetsodha** [comment]
Resolved
