### ISSUE TITLE
Not Support In Laravel 10

### ISSUE THREAD

**Issue by ahmedmohsen90** [kawankoding/laravel-fcm#60]
Not Support In Laravel 10
im trying to install it on laravel 10 but i found this error

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires kawankoding/laravel-fcm ^0.2.7 -> satisfiable by kawankoding/laravel-fcm[0.2.7].
    - kawankoding/laravel-fcm 0.2.7 requires illuminate/support ^5.1|^6.0|^7.0|^8.0|^9.0 -> found illuminate/support[v5.1.1, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require kawankoding/laravel-fcm:*" to figure out if any version is installable, or "composer require kawankoding/laravel-fcm:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by mai92** [comment]
added, support for Laravel 10, please check it again
