### ISSUE TITLE
Send to Android/iOS not working

### ISSUE THREAD

**Issue by be-geeky** [kawankoding/laravel-fcm#7]
I have tested this package. It is working fine over browsers but not in Android/iOS Devices. Am I missing something?

**Comment by mai92** [comment]
have you set the fcm key for each devices ? sorry for late reply

**Comment by be-geeky** [comment]
Thank you. Are you talking about Device Token? if that then I checked by adding those tokens in `$recipients` Array. If you are talking about other keys then can you please guide me? Thank you. Great work by the way.

**Comment by mai92** [comment]
firebase cloud message token or key not the device token i mean, so you need to store firebase token you get from device to database for every user so you can can the notifications 

thanks @be-geeky
